#!/bin/env python
from SCons.Script import Environment
from os import path
import sys

env = Environment()

# Set the target path and name.
target_path = "../bin/"
target_name = "libDokiGDE"

# Set the compiler and flags.
env.Append(CPPPATH=["inc"])  # Add the inc folder to the include path.
env.Append(CFLAGS=["-O0", "-g"])  # Make it a Debug build.
# env.Append(CFLAGS=["-O4"]) # Make it a Release build

# Use Clang on macOS.
if sys.platform == "darwin":
    env["CC"] = "clang"

# Add all C files in "src" folder as sources.
sources = env.Glob("src/*.c")

# Create a shared library.
library = env.SharedLibrary(
    target=path.join(target_path, target_name),
    source=sources,
)

# Set the library as the default target.
env.Default(library)